### Hello
GET http://localhost:3000/

### Listar libros
GET http://localhost:3000/api/libros

### Autores
GET http://localhost:3000/api/autores/1

### Libros disponibles
GET http://localhost:3000/api/libros?disponible=true
